name: Diag Caller
on:
  push:
    branches: [fix/ci-conformance-ref-73]
permissions:
  contents: read
  id-token: write
jobs:
  call:
    uses: MustardSeedNetworks/.github/.github/workflows/diag-callee.yml@34fde546a3fbfd5587e63e0f3b62506344517106
